# Generated by Django 4.2.5 on 2024-10-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_appointment'),
        ('Patient', '0005_remove_patientprofile_password'),
    ]

    operations = [
    ]
