# Generated by Django 4.2.5 on 2024-10-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_medicalprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='medicalprofile',
            name='medications',
        ),
    ]
