# Generated by Django 4.2.7 on 2024-10-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_remove_patientprofile_email_and_more'),
        ('Patient', '0008_remove_medicalprofile_allergies_and_more'),
    ]

    operations = [
    ]
