# Generated by Django 4.2.7 on 2024-10-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_merge_20241009_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalProfile',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='prev_checkup',
            field=models.DateField(null=True),
        ),
    ]
