# Generated by Django 4.2.5 on 2024-10-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_delete_medicalprofile_patientprofile_prev_checkup'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_category',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('Gynecology', 'Gynecology'), ('Psychiatry', 'Psychiatry')], default='General Physician', max_length=50),
        ),
    ]
